### ISSUE TITLE
hysteria2: support userpass

### ISSUE THREAD

**Issue by superbarney** [MatsuriDayo/NekoBoxForAndroid#646]
## Description suggestions
hysteria2 supports multiple users with their own individual passwords but NekoBox doesn't seem to allow the input for users

## Necessity of recommendations
Is userpass currently supported and I'm doing it wrong?
Thanks.

**Comment by zhanbao2000** [comment]
If you set userpass on your server like this:

```
auth:
  type: userpass
  userpass:
    user1: pass1
    user2: pass2
```

You should fill in `user1:pass1` in your password field.

This works in my version (1.3.0)
